### ISSUE TITLE
Return Set of type String instead of Set of type Object

### ISSUE THREAD

**Issue by gshaw1997** [Cyber4All/clark-taxonomy#1]
`taxonomy-json.ts` should be restructured to contain arrays of strings. The current structure where the property name of the objects in the array is the lowercased/camelCased version of the property's value is redundant and leads to inefficient checking of whether or not a value exists within the taxonomy.

Rationale 
With the current structure, there is currently no clean way to verify that a string value is within a Set because the strings are nested in an Object, so in order to perform the check one must iterate over the set and then iterate over the Objects' keys/values within the set and perform a check on each key/value to match.
If the structure was changed to a Set of type String one would only have to iterate over the set or just utilize the Set.has() method.

**Comment by DonSeannelly** [comment]
Isn't this what we had before, which needed to be changed? See the repo [before @KolbeML updated](https://github.com/Cyber4All/clark-taxonomy/tree/182f9295735396e50642abf1c0b930f0919b23e4) and more specifically, [taxonomy.ts](https://github.com/Cyber4All/clark-taxonomy/blob/182f9295735396e50642abf1c0b930f0919b23e4/lib/taxonomy.ts).

@gshaw1997 are you suggesting a revert or a modified structure?
