### ISSUE TITLE
Remove CCECC and Military Academy from SO database

### ISSUE THREAD

**Issue by siddharthkaza** [Cyber4All/clark-taxonomy#5]
<img width="1008" alt="screen shot 2018-03-20 at 8 37 23 pm" src="https://user-images.githubusercontent.com/2423261/37689986-a794d504-2c7e-11e8-805c-a709951b5647.png">

**Comment by gshaw1997** [comment]
@DonSeannelly @nrwinner I'll delete them from the database. The dropdowns will have to be updated to reflect that.

**Comment by DonSeannelly** [comment]
@gshaw1997 I'll handle the dropdowns

**Comment by DonSeannelly** [comment]
Closed via Cyber4All/clark-client@85fb36a953cd096c5a5b3fee82d3545ce5bd4194
